version: "3.8"

services:
  # Приложение
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Пробрасываем порт для приложения
    env_file:
      - .env
    depends_on:
      - db
      - ollama
      - ollama-pull
    environment:
      DATABASE_URL: ${DATABASE_URL}
      OLLAMA_URL: ${OLLAMA_BASE_URL}
    volumes:
      - .:/app # Проброс текущей директории для разработки
    command: npx ts-node app.ts

  # PostgreSQL
  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data

  # Ollama
  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    ports:
      - "11434:11434"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ollama_data:/root/.ollama

  ollama-pull:
    image: docker/genai:ollama-pull
    env_file:
      - .env
    environment:
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL}
      LLM: ${LLM}
      

volumes:
  db_data:
  ollama_data:

