version: "3.8"

services:
  # Приложение
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Пробрасываем порт для приложения
    env_file:
      - .env
    depends_on:
      - db
      - ollama
    environment:
      DATABASE_URL: ${DATABASE_URL}
      OLLAMA_URL: ${OLLAMA_URL}
    volumes:
      - .:/app # Проброс текущей директории для разработки
    command: npx ts-node app.ts

  # PostgreSQL
  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data

  # Ollama
  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    ports:
      - "11434:11434"
    healthcheck:
      test: ["CMD", "ollama", "--version"]
    volumes:
      - ./ollama_data:/data

volumes:
  db_data:
